apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: yutlyqja3-python
  janus-idp.io/tekton: yutlyqja3-python
  backstage.io/kubernetes-id: yutlyqja3-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yutlyqja3-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
